import { ArrowRight, Ticket, Send, Trophy } from 'lucide-react'
import { BlurText, CountUp, Magnetic, Reveal } from '../components/fx'
import { Link } from 'react-router-dom'

const steps = [
 { icon: <Ticket/>, title: 'Pass the course.', body: 'Finish Systems Thinking for Makers and claim your certificate — it’s your ticket in. Every application starts here.', cta: 'Earn your ticket', to: '/academy/systems-thinking' },
 { icon: <Send/>, title: 'Show us a fragment.', body: 'A sketch, prototype, paragraph, or recording of the idea you cannot leave alone. Imperfect is welcome.', cta: 'Prepare your entry', to: '/academy' },
 { icon: <Trophy/>, title: 'Make your next move.', body: 'We invite five makers into the program before September. Winners are announced in the community hall.', cta: 'See past winners', to: '/dashboard' },
]

export function Campaign() { return <main className="campaign"><section className="campaign-hero constellation"><h1><BlurText text="FCA Maker Grant"/></h1><Reveal delay={250}><div className="campaign-badges"><span>100,000-XP grant</span><span>2-week program</span><span>Private crew channel</span><span>Open worldwide</span></div></Reveal><Reveal delay={380}><Magnetic><Link className="button gold-button raised" to="/academy/systems-thinking">Apply for maker grant</Link></Magnetic></Reveal><Reveal delay={500}><p className="campaign-sub"><em>You have talent. All you need is to show it.</em><br/>Post your work — real or wild, any skill, any style. <em>Win big: 100,000 XP for life</em>, 2 weeks of live training with the team behind Future Creators Academy.</p></Reveal></section>
<section className="campaign-benefits section"><Reveal><article><h3>100,000 XP. Day one.</h3><p>The full grant lands the moment you’re in. Spend it your way — two weeks with the crew will show you how to spend it well.</p><div className="benefit-visual laurel"><span>❧</span><b><CountUp to={100000}/><small>XP</small></b><span>❧</span></div></article></Reveal><Reveal delay={100}><article><h3>The private crew channel</h3><p>A closed channel with the FCA creative team: live sessions, work breakdowns, and direct feedback on your projects.</p><div className="benefit-visual media"><div className="media-thumb"/><div className="avatar-stack"><i/><i/><i>+12</i></div></div></article></Reveal><Reveal delay={200}><article><h3>Open worldwide</h3><p>18+, any creative background. No portfolio required — we select on the work itself.</p><div className="benefit-visual globe"><div className="globe-orb"/></div></article></Reveal></section>
<section className="apply-flow section"><div className="flow-intro"><h2>HOW TO ENTER</h2><p>From the course to the crew channel — three steps, no shortcuts.</p><Link className="button gold-button raised" to="/academy/systems-thinking">Apply now</Link></div><ol>{steps.map((step, index) => <Reveal delay={index * 120} key={step.title}><li><span className="step-label">STEP {index + 1}</span><span className="step-icon">{step.icon}</span><div><h3><b>{step.title}</b> {step.body}</h3><Link className="button light" to={step.to}>{step.cta}</Link></div></li></Reveal>)}</ol></section>
<section className="campaign-cta"><h2>The world has enough<br/>almost-ideas.</h2><Link className="button gold-button raised" to="/academy/systems-thinking">Start your application <ArrowRight/></Link></section></main> }
